import bcrypt from 'bcryptjs';
import { 
  User, 
  StudentProfile, 
  Company, 
  Job, 
  Application, 
  NotificationItem, 
  Category, 
  LocationItem 
} from '../types';

// Pre-hashed password for "password123" for instantaneous initial seeding
const DEFAULT_PASSWORD_HASH = bcrypt.hashSync('password123', 10);

export const SEED_CATEGORIES: Category[] = [
  { category_id: 1, name: 'Software Development', name_amharic: 'የሶፍትዌር ልማት', slug: 'software-development', icon_name: 'Code2', job_count: 14 },
  { category_id: 2, name: 'IT & Networking', name_amharic: 'የመረጃ ቴክኖሎጂ እና ኔትወርክ', slug: 'it-networking', icon_name: 'Server', job_count: 8 },
  { category_id: 3, name: 'Accounting & Finance', name_amharic: 'ሂሳብ እና ፋይናንስ', slug: 'accounting-finance', icon_name: 'Calculator', job_count: 11 },
  { category_id: 4, name: 'Engineering & Construction', name_amharic: 'ኢንጂነሪንግ እና ኮንስትራክሽን', slug: 'engineering-construction', icon_name: 'Building2', job_count: 6 },
  { category_id: 5, name: 'Marketing & Sales', name_amharic: 'ማርኬቲንግ እና ሽያጭ', slug: 'marketing-sales', icon_name: 'TrendingUp', job_count: 9 },
  { category_id: 6, name: 'Healthcare & Medical', name_amharic: 'የጤና እና ህክምና', slug: 'healthcare-medical', icon_name: 'Stethoscope', job_count: 5 },
  { category_id: 7, name: 'Design & Creative', name_amharic: 'ዲዛይን እና ስነ-ጥበብ', slug: 'design-creative', icon_name: 'Palette', job_count: 7 },
  { category_id: 8, name: 'Internships & Entry Level', name_amharic: 'የተግባር ልምምድ (ኢንተርንሺፕ)', slug: 'internships', icon_name: 'Sparkles', job_count: 12 },
  { category_id: 9, name: 'Banking & FinTech', name_amharic: 'ባንክ እና ፊንቴክ', slug: 'banking-fintech', icon_name: 'Landmark', job_count: 8 },
  { category_id: 10, name: 'NGO & Social Impact', name_amharic: 'የግብረ-ሰናይ እና ማህበረሰብ', slug: 'ngo-social-impact', icon_name: 'HeartHandshake', job_count: 4 },
];

export const SEED_LOCATIONS: LocationItem[] = [
  { location_id: 1, city: 'Addis Ababa', city_amharic: 'አዲስ አበባ', subcity: 'Bole', region: 'Addis Ababa', is_popular: true },
  { location_id: 2, city: 'Addis Ababa', city_amharic: 'አዲስ አበባ', subcity: 'Kirkos / Kazanchis', region: 'Addis Ababa', is_popular: true },
  { location_id: 3, city: 'Addis Ababa', city_amharic: 'አዲስ አበባ', subcity: 'Yeka', region: 'Addis Ababa', is_popular: true },
  { location_id: 4, city: 'Addis Ababa', city_amharic: 'አዲስ አበባ', subcity: 'Arada / Piassa', region: 'Addis Ababa', is_popular: true },
  { location_id: 5, city: 'Addis Ababa', city_amharic: 'አዲስ አበባ', subcity: 'Nifas Silk-Lafto', region: 'Addis Ababa', is_popular: true },
  { location_id: 6, city: 'Addis Ababa', city_amharic: 'አዲስ አበባ', subcity: 'Lideta', region: 'Addis Ababa', is_popular: false },
  { location_id: 7, city: 'Hawassa', city_amharic: 'ሀዋሳ', subcity: 'City Center', region: 'Sidama', is_popular: true },
  { location_id: 8, city: 'Dire Dawa', city_amharic: 'ድሬዳዋ', subcity: 'Kezira', region: 'Dire Dawa', is_popular: true },
  { location_id: 9, city: 'Bahir Dar', city_amharic: 'ባህር ዳር', subcity: 'Gish Abay', region: 'Amhara', is_popular: true },
  { location_id: 10, city: 'Adama', city_amharic: 'አዳማ', subcity: 'Bole / Dembela', region: 'Oromia', is_popular: true },
  { location_id: 11, city: 'Mekelle', city_amharic: 'መቐለ', subcity: 'Ayder', region: 'Tigray', is_popular: false },
  { location_id: 12, city: 'Jimma', city_amharic: 'ጅማ', subcity: 'Hermata', region: 'Oromia', is_popular: false },
];

export const SEED_USERS: User[] = [
  // 1. Student / Job Seeker 1
  {
    user_id: 1,
    full_name: 'Yohannes Tadesse',
    email: 'yohannes@student.aau.edu.et',
    role: 'JOB_SEEKER',
    phone_number: '+251 91 123 4567',
    avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
    is_active: true,
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  // 2. Student / Job Seeker 2
  {
    user_id: 2,
    full_name: 'Bethlehem Haile',
    email: 'bethlehem.haile@gmail.com',
    role: 'JOB_SEEKER',
    phone_number: '+251 92 345 6789',
    avatar_url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=300&q=80',
    is_active: true,
    created_at: new Date(Date.now() - 25 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  // 3. Student / Job Seeker 3
  {
    user_id: 3,
    full_name: 'Dawit Abebe',
    email: 'dawit.abebe@astu.edu.et',
    role: 'JOB_SEEKER',
    phone_number: '+251 93 456 7890',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
    is_active: true,
    created_at: new Date(Date.now() - 15 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  // 4. Employer 1 (EthioTech Solutions)
  {
    user_id: 4,
    full_name: 'Selamawit Bekele (HR)',
    email: 'hr@ethiotech.et',
    role: 'EMPLOYER',
    phone_number: '+251 11 661 2233',
    avatar_url: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=300&q=80',
    is_active: true,
    created_at: new Date(Date.now() - 60 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  // 5. Employer 2 (Kifiya FinTech)
  {
    user_id: 5,
    full_name: 'Nahom Girma (Tech Lead)',
    email: 'talent@kifiya.et',
    role: 'EMPLOYER',
    phone_number: '+251 11 550 4488',
    avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80',
    is_active: true,
    created_at: new Date(Date.now() - 45 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  // 6. Admin
  {
    user_id: 6,
    full_name: 'Solomon Mengistu',
    email: 'admin@hirehub.et',
    role: 'ADMIN',
    phone_number: '+251 91 000 0001',
    avatar_url: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=300&q=80',
    is_active: true,
    created_at: new Date(Date.now() - 120 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const SEED_PASSWORDS: Record<number, string> = {
  1: DEFAULT_PASSWORD_HASH,
  2: DEFAULT_PASSWORD_HASH,
  3: DEFAULT_PASSWORD_HASH,
  4: DEFAULT_PASSWORD_HASH,
  5: DEFAULT_PASSWORD_HASH,
  6: DEFAULT_PASSWORD_HASH,
};

export const SEED_STUDENT_PROFILES: StudentProfile[] = [
  {
    profile_id: 1,
    user_id: 1,
    headline: 'Junior Full-Stack Developer | React & Node.js | AAU Software Eng. Graduate',
    bio: 'Passionate software developer from Addis Ababa University with hands-on experience building web and mobile applications. Enthusiastic about creating modern digital products that empower Ethiopian businesses and communities.',
    city_subcity: 'Addis Ababa (Bole)',
    portfolio_url: 'https://yohannes-dev.et',
    github_url: 'https://github.com/yohannes-tadesse',
    linkedin_url: 'https://linkedin.com/in/yohannes-tadesse-et',
    cv_url: '/uploads/resumes/yohannes_tadesse_cv.pdf',
    cv_filename: 'Yohannes_Tadesse_Software_Engineer_CV.pdf',
    cv_extracted_text: `YOHANNES TADESSE
Addis Ababa, Ethiopia | yohannes@student.aau.edu.et | +251 91 123 4567 | github.com/yohannes-tadesse

SUMMARY
Graduating Software Engineering student from Addis Ababa University (AAU) with solid foundations in JavaScript/TypeScript, React, Node.js, Express, and SQL. Built multiple university and freelance applications including an e-commerce microservices demo and an Ethiopian telebirr payment simulation.

EDUCATION
Addis Ababa University (AAU) - Addis Ababa Institute of Technology (AAiT)
B.Sc. in Software Engineering, Cumulative GPA: 3.82 / 4.0
Sep 2021 – Jul 2025

TECHNICAL SKILLS
• Programming: JavaScript (ES6+), TypeScript, Python, SQL, C++, HTML5, CSS3/Tailwind CSS
• Frontend: React.js, Next.js, Redux Toolkit, React Router, Vite, Framer Motion
• Backend: Node.js, Express.js, RESTful APIs, JWT Authentication, Multer
• Databases: MySQL, PostgreSQL, MongoDB
• Tools & Methodologies: Git & GitHub, Docker (Basics), Postman, Agile/Scrum

EXPERIENCE & PROJECTS
Software Engineering Intern | Addis Software PLC (Bole, Addis Ababa)
Jul 2024 – Oct 2024
• Developed React frontend features for a client onboarding dashboard reducing signup friction by 35%.
• Implemented robust Express REST APIs and integrated PostgreSQL queries for user role-based access.
• Collaborated in weekly sprints and code reviews with senior engineering teams.

Ethiopian SME Inventory & Invoicing Web App (Final Year Capstone Project)
• Built a full-stack web application supporting dual English/Amharic invoicing and receipt generation.
• Integrated local tax calculation (VAT 15%) and automated PDF generation for Ethiopian merchants.

LANGUAGES
• Amharic (Native), English (Fluent / Professional), Afaan Oromoo (Conversational)`,
    profile_completion_percentage: 95,
    education: [
      {
        education_id: 1,
        profile_id: 1,
        institution: 'Addis Ababa University (AAiT)',
        degree: 'B.Sc. in Software Engineering',
        field_of_study: 'Computer Science & Software Engineering',
        start_year: 2021,
        end_year: 2025,
        is_current: false,
        gpa_or_grade: '3.82 / 4.0',
      },
    ],
    experience: [
      {
        experience_id: 1,
        profile_id: 1,
        title: 'Software Developer Intern',
        company_name: 'Addis Software PLC',
        location: 'Addis Ababa, Bole',
        start_date: '2024-07-01',
        end_date: '2024-10-30',
        is_current: false,
        description: 'Built React UI components, optimized REST API payloads, and wrote unit tests for merchant portals.',
      },
    ],
    certifications: [
      {
        cert_id: 1,
        name: 'Meta Front-End Developer Professional Certificate',
        issuing_org: 'Coursera / Meta',
        issue_date: '2024-05-15',
        credential_url: 'https://coursera.org/verify/meta-frontend-yohannes',
      },
      {
        cert_id: 2,
        name: 'Full Stack Open (Deep Dive into Modern Web Development)',
        issuing_org: 'University of Helsinki',
        issue_date: '2024-08-20',
      },
    ],
    languages: [
      { language_id: 1, language_name: 'Amharic (አማርኛ)', proficiency: 'NATIVE' },
      { language_id: 2, language_name: 'English', proficiency: 'FLUENT' },
      { language_id: 3, language_name: 'Afaan Oromoo', proficiency: 'CONVERSATIONAL' },
    ],
    skills: ['React', 'TypeScript', 'JavaScript', 'Node.js', 'Express.js', 'Tailwind CSS', 'SQL', 'MySQL', 'Git & GitHub', 'RESTful APIs', 'Next.js'],
  },
  {
    profile_id: 2,
    user_id: 2,
    headline: 'UI/UX & Product Designer | Figma, Design Systems & Frontend Enthusiast',
    bio: 'Creative product designer focused on creating intuitive, human-centered digital experiences for African users. Strong visual design skills backed by practical HTML/Tailwind styling know-how.',
    city_subcity: 'Addis Ababa (Kazanchis)',
    portfolio_url: 'https://bethlehem-designs.et',
    github_url: 'https://github.com/bethlehem-h',
    linkedin_url: 'https://linkedin.com/in/bethlehem-haile',
    cv_url: '/uploads/resumes/bethlehem_haile_cv.pdf',
    cv_filename: 'Bethlehem_Haile_UIUX_Designer_CV.pdf',
    cv_extracted_text: `BETHLEHEM HAILE
Addis Ababa, Ethiopia | bethlehem.haile@gmail.com | +251 92 345 6789 | behance.net/bethlehemh

PROFILE
Creative UI/UX & Product Designer with 2+ years of experience designing mobile and responsive web applications for Ethiopian tech startups. Skilled in user research, wireframing, high-fidelity interactive prototyping in Figma, and design systems.

EDUCATION
Adama Science and Technology University (ASTU)
B.Sc. in Computer Science and Engineering | Graduated 2024

SKILLS
• Design: Figma, Adobe XD, Design Systems, User Personas, Information Architecture, Prototyping
• Frontend: HTML5, CSS3, Tailwind CSS, Responsive Web Design
• Research: User Testing, Heuristic Evaluation, Accessibility (WCAG)

NOTABLE PROJECTS
• Telebirr Merchant Redesign (Concept): Streamlined transaction flow for 500+ daily street vendors.
• Ride Ethiopia Driver App Concept: Designed high-contrast interface for daylight readability.`,
    profile_completion_percentage: 85,
    education: [
      {
        education_id: 2,
        profile_id: 2,
        institution: 'Adama Science and Technology University (ASTU)',
        degree: 'B.Sc. in Computer Science',
        field_of_study: 'Human Computer Interaction',
        start_year: 2020,
        end_year: 2024,
        is_current: false,
        gpa_or_grade: '3.65 / 4.0',
      },
    ],
    experience: [
      {
        experience_id: 2,
        profile_id: 2,
        title: 'Junior UI/UX Designer',
        company_name: 'ZayRide Innovation Lab',
        location: 'Addis Ababa',
        start_date: '2024-01-10',
        end_date: '2024-11-20',
        is_current: false,
        description: 'Conducted user interviews with 40+ Ethiopian drivers and created production-ready Figma design libraries.',
      },
    ],
    certifications: [
      {
        cert_id: 3,
        name: 'Google UX Design Professional Certificate',
        issuing_org: 'Coursera / Google',
        issue_date: '2023-11-10',
      },
    ],
    languages: [
      { language_id: 4, language_name: 'Amharic', proficiency: 'NATIVE' },
      { language_id: 5, language_name: 'English', proficiency: 'FLUENT' },
      { language_id: 6, language_name: 'Tigrinya', proficiency: 'CONVERSATIONAL' },
    ],
    skills: ['Figma', 'UI/UX Design', 'User Research', 'Design Systems', 'Tailwind CSS', 'HTML/CSS', 'Prototyping'],
  },
  {
    profile_id: 3,
    user_id: 3,
    headline: 'Junior Accountant & Financial Analyst | IFRS & Peachtree Certified',
    bio: 'Detail-oriented accounting graduate from Hawassa University with deep knowledge of Ethiopian tax regulations (ERCA/MoR), IFRS reporting standards, and digital financial management.',
    city_subcity: 'Hawassa / Addis Ababa',
    portfolio_url: '',
    github_url: '',
    linkedin_url: 'https://linkedin.com/in/dawit-abebe-finance',
    profile_completion_percentage: 70,
    education: [
      {
        education_id: 3,
        profile_id: 3,
        institution: 'Hawassa University',
        degree: 'B.A. in Accounting and Finance',
        field_of_study: 'Corporate Finance & Auditing',
        start_year: 2021,
        end_year: 2025,
        is_current: false,
        gpa_or_grade: '3.75 / 4.0',
      },
    ],
    experience: [],
    certifications: [
      {
        cert_id: 4,
        name: 'Peachtree Accounting & IFRS Certification',
        issuing_org: 'Ethiopian Accounting & Auditing Board (AABE)',
        issue_date: '2024-09-01',
      },
    ],
    languages: [
      { language_id: 7, language_name: 'Amharic', proficiency: 'NATIVE' },
      { language_id: 8, language_name: 'English', proficiency: 'FLUENT' },
    ],
    skills: ['Financial Reporting', 'IFRS Standards', 'Tax Filing (ERCA/MoR)', 'Peachtree / QuickBooks', 'Excel Financial Modeling'],
  },
];

export const SEED_COMPANIES: Company[] = [
  {
    company_id: 1,
    user_id: 4,
    name: 'EthioTech Solutions PLC',
    name_amharic: 'ኢትዮቴክ ሶሉሽንስ ኃ/የተ/የግ/ማ',
    slug: 'ethiotech-solutions',
    logo_url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=150&q=80',
    cover_url: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200&q=80',
    industry: 'Software Development & Cloud',
    website_url: 'https://ethiotech.et',
    about: 'EthioTech Solutions is one of Addis Ababa’s fastest growing technology powerhouses. We build enterprise cloud solutions, government digital transformation platforms, and high-performance financial systems across East Africa.',
    company_size: '51-200',
    founded_year: 2018,
    city: 'Addis Ababa',
    subcity: 'Bole (Near Edna Mall, Mega Building)',
    address_details: 'Floor 7, Edna Commercial Tower, Bole Subcity',
    approval_status: 'APPROVED',
    created_at: new Date(Date.now() - 90 * 86400000).toISOString(),
    open_positions_count: 5,
  },
  {
    company_id: 2,
    user_id: 5,
    name: 'Kifiya Financial Technology',
    name_amharic: 'ኪፊያ ፋይናንሻል ቴክኖሎጂ',
    slug: 'kifiya-fintech',
    logo_url: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=150&q=80',
    cover_url: 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1200&q=80',
    industry: 'Banking & FinTech',
    website_url: 'https://kifiya.et',
    about: 'Kifiya is a pioneering Ethiopian technology and digital services company delivering accessible digital financial infrastructure, micro-lending platforms, and agricultural tech for millions of citizens.',
    company_size: '201-500',
    founded_year: 2012,
    city: 'Addis Ababa',
    subcity: 'Kirkos (Kazanchis, Nigist Towers)',
    address_details: '5th Floor, Nigist Towers, Kazanchis',
    approval_status: 'APPROVED',
    created_at: new Date(Date.now() - 100 * 86400000).toISOString(),
    open_positions_count: 4,
  },
  {
    company_id: 3,
    user_id: 4,
    name: 'Dashen Innovation Labs',
    name_amharic: 'ዳሽን ባንክ የዲጂታል ፈጠራ ማዕከል',
    slug: 'dashen-innovation-labs',
    logo_url: 'https://images.unsplash.com/photo-1541701494587-cb58502866ab?auto=format&fit=crop&w=150&q=80',
    cover_url: 'https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=1200&q=80',
    industry: 'Banking & Microfinance',
    website_url: 'https://dashenbanksc.com',
    about: 'The dedicated digital and R&D branch of Dashen Bank S.C., engineering next-generation omni-channel mobile banking, AI fraud prevention, and seamless open banking APIs.',
    company_size: '500+',
    founded_year: 2020,
    city: 'Addis Ababa',
    subcity: 'Kirkos (Financial District, Dashen HQ)',
    address_details: 'Dashen Bank Tower, Sudan Street',
    approval_status: 'APPROVED',
    created_at: new Date(Date.now() - 80 * 86400000).toISOString(),
    open_positions_count: 3,
  },
  {
    company_id: 4,
    user_id: 5,
    name: 'Gebeya Tech Network',
    name_amharic: 'ገበያ የቴክኖሎጂ አውታር',
    slug: 'gebeya-tech',
    logo_url: 'https://images.unsplash.com/photo-1560179707-f14e90ef3623?auto=format&fit=crop&w=150&q=80',
    cover_url: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=1200&q=80',
    industry: 'IT Talent & Training',
    website_url: 'https://gebeya.com',
    about: 'Pan-African SaaS marketplace connecting vetted Ethiopian software engineering talent, product managers, and cloud architects with global and continental enterprises.',
    company_size: '51-200',
    founded_year: 2016,
    city: 'Addis Ababa',
    subcity: 'Bole (Near Airport Road)',
    address_details: 'Sinan Commercial Building, Bole',
    approval_status: 'APPROVED',
    created_at: new Date(Date.now() - 70 * 86400000).toISOString(),
    open_positions_count: 4,
  },
  {
    company_id: 5,
    user_id: 4,
    name: 'YeneHealth Digital PLC',
    name_amharic: 'የኔ ሄልዝ ዲጂታል',
    slug: 'yenehealth-digital',
    logo_url: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=150&q=80',
    cover_url: 'https://images.unsplash.com/photo-1505751172876-fa1923c5c528?auto=format&fit=crop&w=1200&q=80',
    industry: 'Healthcare & FemTech',
    website_url: 'https://yenehealth.com',
    about: 'The first Ethiopian digital healthcare platform focused on confidential reproductive health tracking, pharmacy e-commerce delivery, and telemedicine consultations in local languages.',
    company_size: '11-50',
    founded_year: 2021,
    city: 'Addis Ababa',
    subcity: 'Yeka (CMC)',
    address_details: 'Sunshine CMC Commercial Complex',
    approval_status: 'APPROVED',
    created_at: new Date(Date.now() - 50 * 86400000).toISOString(),
    open_positions_count: 2,
  },
];

export const SEED_JOBS: Job[] = [
  {
    job_id: 1,
    company_id: 1,
    company_name: 'EthioTech Solutions PLC',
    company_logo: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=150&q=80',
    company_slug: 'ethiotech-solutions',
    company_city: 'Addis Ababa',
    title: 'Frontend React Developer',
    category_id: 1,
    category_name: 'Software Development',
    job_type: 'FULL_TIME',
    experience_level: 'ENTRY_LEVEL',
    location_city: 'Addis Ababa',
    location_subcity: 'Bole',
    workplace_type: 'HYBRID',
    salary_type: 'RANGE',
    salary_min: 22000,
    salary_max: 35000,
    currency: 'ETB',
    description: 'We are seeking an ambitious Junior Frontend Developer to join our core product engineering unit in Bole, Addis Ababa. You will collaborate closely with UI/UX designers and backend engineers to build responsive web portals for enterprise Ethiopian clients.',
    responsibilities: [
      'Build reusable, clean, and accessible UI components in React 18+ and TypeScript.',
      'Integrate RESTful and GraphQL APIs with optimistic UI updates and state management.',
      'Optimize web performance, mobile responsiveness, and cross-browser consistency.',
      'Write clean, maintainable code following team Git workflows and automated CI pipelines.',
      'Participate in agile sprint ceremonies, code reviews, and architectural discussions.',
    ],
    requirements: [
      'B.Sc. in Software Engineering, Computer Science, or equivalent demonstrable project portfolio.',
      'Proficiency in modern JavaScript (ES6+), TypeScript, HTML5, and Tailwind CSS.',
      'Hands-on experience with React.js, React Router, and Axios/Fetch API.',
      'Familiarity with Git/GitHub version control.',
      'Strong problem-solving attitude and willingness to learn quickly.',
    ],
    required_skills: ['React', 'TypeScript', 'JavaScript', 'HTML/CSS', 'Tailwind CSS', 'Git & GitHub'],
    preferred_skills: ['Next.js', 'Framer Motion', 'RESTful APIs', 'Docker (Basics)'],
    benefits: [
      'Competitive monthly salary in ETB with biannual performance reviews',
      'Hybrid work model (3 days in our modern Bole office, 2 days remote)',
      'High-speed fiber internet allowance for home office days',
      'Comprehensive private health insurance coverage (Med-Net Ethiopia)',
      'Learning budget for Coursera/Udemy certifications and tech conferences',
    ],
    deadline: new Date(Date.now() + 25 * 86400000).toISOString().split('T')[0],
    status: 'OPEN',
    is_featured: true,
    views_count: 342,
    applications_count: 14,
    created_at: new Date(Date.now() - 3 * 86400000).toISOString(),
  },
  {
    job_id: 2,
    company_id: 2,
    company_name: 'Kifiya Financial Technology',
    company_logo: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=150&q=80',
    company_slug: 'kifiya-fintech',
    company_city: 'Addis Ababa',
    title: 'Junior Backend Engineer (Node.js & Express)',
    category_id: 1,
    category_name: 'Software Development',
    job_type: 'FULL_TIME',
    experience_level: 'ENTRY_LEVEL',
    location_city: 'Addis Ababa',
    location_subcity: 'Kirkos (Kazanchis)',
    workplace_type: 'ON_SITE',
    salary_type: 'RANGE',
    salary_min: 25000,
    salary_max: 38000,
    currency: 'ETB',
    description: 'Join Kifiya FinTech’s payment gateway team to build resilient microservices, secure transaction processing endpoints, and database pipelines processing thousands of daily transactions across Ethiopia.',
    responsibilities: [
      'Design and implement secure RESTful APIs using Node.js, Express.js, and TypeScript.',
      'Write optimized database queries and schema migrations in PostgreSQL / MySQL.',
      'Implement JWT authentication, rate limiting, and role-based access controls.',
      'Integrate with third-party payment rails, SMS gateways, and core banking systems.',
      'Monitor application logs and debug production issues promptly.',
    ],
    requirements: [
      'Degree in Computer Science, Software Engineering, or related technical field.',
      'Solid command of Node.js, Express.js, and asynchronous JavaScript.',
      'Experience with relational databases (MySQL or PostgreSQL).',
      'Understanding of API security best practices and data validation.',
      'Good communication skills in Amharic and English.',
    ],
    required_skills: ['Node.js', 'Express.js', 'SQL', 'PostgreSQL', 'RESTful APIs', 'JWT Authentication'],
    preferred_skills: ['Docker', 'Redis', 'TypeScript', 'Telebirr/CBE API Integration'],
    benefits: [
      'Attractive salary and annual performance bonus',
      'Subsidized cafeteria meals at Kazanchis headquarters',
      'Health insurance including dental and vision',
      'Continuous mentorship from veteran FinTech architects',
    ],
    deadline: new Date(Date.now() + 20 * 86400000).toISOString().split('T')[0],
    status: 'OPEN',
    is_featured: true,
    views_count: 480,
    applications_count: 22,
    created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
  },
  {
    job_id: 3,
    company_id: 1,
    company_name: 'EthioTech Solutions PLC',
    company_logo: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=150&q=80',
    company_slug: 'ethiotech-solutions',
    company_city: 'Addis Ababa',
    title: 'Software Development Internship — 2026 Batch',
    category_id: 8,
    category_name: 'Internships & Entry Level',
    job_type: 'INTERNSHIP',
    experience_level: 'INTERN',
    location_city: 'Addis Ababa',
    location_subcity: 'Bole',
    workplace_type: 'ON_SITE',
    salary_type: 'EXACT',
    salary_exact: 12000,
    currency: 'ETB',
    description: 'A structured 4-month paid internship program specifically designed for Ethiopian 4th/5th year university students and fresh graduates (AAU, ASTU, Hawassa, Bahir Dar, Mekelle, Jimma, etc.). Gain real-world production experience under 1-on-1 mentorship.',
    responsibilities: [
      'Participate in real client software development projects using modern stacks.',
      'Complete weekly code assignments, pair programming, and architectural workshops.',
      'Build a capstone team project deployed on live cloud infrastructure.',
      'Receive weekly feedback and career coaching from senior engineers.',
    ],
    requirements: [
      'Currently enrolled final-year student or graduate in Computer Science, Software Engineering, or IT.',
      'Demonstrated passion for coding (personal GitHub projects, university coursework, or hackathons).',
      'Knowledge of basic web development fundamentals (HTML, CSS, JavaScript or Python).',
      'Available full-time (Monday to Friday) for 4 months.',
    ],
    required_skills: ['JavaScript', 'HTML/CSS', 'Git & GitHub', 'Problem Solving'],
    preferred_skills: ['React', 'Node.js', 'Python'],
    benefits: [
      'Monthly internship stipend of ETB 12,000',
      'Fast-track offer for full-time Junior Developer role upon graduation',
      'Free lunch and coffee in our Bole office',
      'Official Certificate of Internship Completion and recommendation letter',
    ],
    deadline: new Date(Date.now() + 15 * 86400000).toISOString().split('T')[0],
    status: 'OPEN',
    is_featured: true,
    views_count: 890,
    applications_count: 56,
    created_at: new Date(Date.now() - 7 * 86400000).toISOString(),
  },
  {
    job_id: 4,
    company_id: 4,
    company_name: 'Gebeya Tech Network',
    company_logo: 'https://images.unsplash.com/photo-1560179707-f14e90ef3623?auto=format&fit=crop&w=150&q=80',
    company_slug: 'gebeya-tech',
    company_city: 'Addis Ababa',
    title: 'UI/UX Product Designer',
    category_id: 7,
    category_name: 'Design & Creative',
    job_type: 'FULL_TIME',
    experience_level: 'MID_LEVEL',
    location_city: 'Addis Ababa',
    location_subcity: 'Bole',
    workplace_type: 'HYBRID',
    salary_type: 'RANGE',
    salary_min: 28000,
    salary_max: 45000,
    currency: 'ETB',
    description: 'We are seeking a talented UI/UX Product Designer who can turn complex workflows into delightful, culturally intuitive digital products for African consumers, farmers, and business owners.',
    responsibilities: [
      'Lead end-to-end design for web and mobile products from research to final Figma delivery.',
      'Conduct user interviews and usability tests with Ethiopian users in Amharic and English.',
      'Maintain and expand our multi-brand Figma design system and component libraries.',
      'Collaborate closely with product managers and frontend developers during implementation.',
    ],
    requirements: [
      '2+ years of demonstrable product design experience with a portfolio of live or conceptual work.',
      'Mastery of Figma (auto-layout, components, variables, interactive prototyping).',
      'Strong understanding of accessibility, typography, and responsive grid layouts.',
      'Ability to clearly communicate design decisions to stakeholders.',
    ],
    required_skills: ['Figma', 'UI/UX Design', 'Design Systems', 'User Research', 'Prototyping'],
    preferred_skills: ['Tailwind CSS', 'Framer Motion', 'Micro-interactions'],
    benefits: [
      'Competitive salary in ETB + stock options grant',
      'Top-tier Apple MacBook Pro workstation provided',
      'Flexible working hours with hybrid schedule',
      'Annual design education allowance',
    ],
    deadline: new Date(Date.now() + 30 * 86400000).toISOString().split('T')[0],
    status: 'OPEN',
    is_featured: false,
    views_count: 210,
    applications_count: 9,
    created_at: new Date(Date.now() - 4 * 86400000).toISOString(),
  },
  {
    job_id: 5,
    company_id: 3,
    company_name: 'Dashen Innovation Labs',
    company_logo: 'https://images.unsplash.com/photo-1541701494587-cb58502866ab?auto=format&fit=crop&w=150&q=80',
    company_slug: 'dashen-innovation-labs',
    company_city: 'Addis Ababa',
    title: 'Junior Accounting & Tax Compliance Officer',
    category_id: 3,
    category_name: 'Accounting & Finance',
    job_type: 'FULL_TIME',
    experience_level: 'ENTRY_LEVEL',
    location_city: 'Addis Ababa',
    location_subcity: 'Kirkos',
    workplace_type: 'ON_SITE',
    salary_type: 'RANGE',
    salary_min: 18000,
    salary_max: 26000,
    currency: 'ETB',
    description: 'Dashen Innovation Labs is recruiting a meticulous Junior Accountant to handle digital financial record-keeping, VAT/Withholding tax declarations with Ministry of Revenues (MoR), and monthly bank reconciliations.',
    responsibilities: [
      'Prepare monthly financial statements, ledger entries, and bank reconciliations.',
      'Ensure 100% compliance with Ethiopian Ministry of Revenues (MoR) tax filing deadlines.',
      'Maintain asset registers and audit trails in accordance with IFRS standards.',
      'Assist external and internal audit teams during quarterly evaluations.',
    ],
    requirements: [
      'B.A. in Accounting, Finance, or Banking from an accredited Ethiopian University.',
      'Certified in Peachtree Accounting or QuickBooks.',
      'Thorough knowledge of Ethiopian tax laws (VAT, WHT, Payroll Tax, Profit Tax).',
      'Proficient in Microsoft Excel (Pivot tables, VLOOKUP/XLOOKUP, formulas).',
    ],
    required_skills: ['Financial Reporting', 'IFRS Standards', 'Tax Filing (ERCA/MoR)', 'Peachtree / QuickBooks'],
    preferred_skills: ['Excel Financial Modeling', 'Auditing Basics'],
    benefits: [
      'Banking industry standard compensation and loan privileges',
      'Full medical coverage for employee and immediate dependents',
      'Annual profit-sharing bonus (Dashen Bank policy)',
      'Clear career advancement path to Senior Financial Analyst',
    ],
    deadline: new Date(Date.now() + 18 * 86400000).toISOString().split('T')[0],
    status: 'OPEN',
    is_featured: false,
    views_count: 310,
    applications_count: 18,
    created_at: new Date(Date.now() - 6 * 86400000).toISOString(),
  },
  {
    job_id: 6,
    company_id: 5,
    company_name: 'YeneHealth Digital PLC',
    company_logo: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=150&q=80',
    company_slug: 'yenehealth-digital',
    company_city: 'Addis Ababa',
    title: 'Mobile App Developer (Flutter / React Native)',
    category_id: 1,
    category_name: 'Software Development',
    job_type: 'FULL_TIME',
    experience_level: 'MID_LEVEL',
    location_city: 'Addis Ababa',
    location_subcity: 'Yeka',
    workplace_type: 'HYBRID',
    salary_type: 'RANGE',
    salary_min: 30000,
    salary_max: 48000,
    currency: 'ETB',
    description: 'Help us scale Ethiopia’s leading health app to over 500,000 active users. You will architect offline-first mobile features, multilingual localized UIs (Amharic, Afaan Oromoo, English), and encrypted health data sync.',
    responsibilities: [
      'Develop clean and performant cross-platform mobile apps for iOS and Android in Flutter or React Native.',
      'Implement robust offline caching (Hive/SQLite) for areas with intermittent Ethiopian connectivity.',
      'Integrate push notifications and local Telebirr/Chapa in-app checkout.',
      'Publish and maintain builds on Google Play Store and Apple App Store.',
    ],
    requirements: [
      '2+ years experience building and publishing production Flutter or React Native apps.',
      'Experience with state management (Riverpod, Bloc, or Redux/Zustand).',
      'Understanding of mobile security, end-to-end encryption, and offline-first storage.',
    ],
    required_skills: ['Flutter', 'Mobile Development', 'TypeScript', 'RESTful APIs', 'Git & GitHub'],
    preferred_skills: ['Dart', 'React Native', 'Offline Caching', 'Telemetry'],
    benefits: [
      'Generous salary in ETB + tech equipment allowance',
      'Flexible hybrid schedule with remote Fridays',
      'Opportunity to build technology saving real lives every day',
    ],
    deadline: new Date(Date.now() + 28 * 86400000).toISOString().split('T')[0],
    status: 'OPEN',
    is_featured: true,
    views_count: 512,
    applications_count: 16,
    created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
  {
    job_id: 7,
    company_id: 1,
    company_name: 'EthioTech Solutions PLC',
    company_logo: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=150&q=80',
    company_slug: 'ethiotech-solutions',
    company_city: 'Hawassa',
    title: 'IT Support & Systems Administrator — Hawassa Branch',
    category_id: 2,
    category_name: 'IT & Networking',
    job_type: 'FULL_TIME',
    experience_level: 'ENTRY_LEVEL',
    location_city: 'Hawassa',
    location_subcity: 'City Center',
    workplace_type: 'ON_SITE',
    salary_type: 'RANGE',
    salary_min: 15000,
    salary_max: 22000,
    currency: 'ETB',
    description: 'We are expanding our regional operations to Hawassa and need an energetic IT Systems Administrator to manage office LAN/WLAN networks, server backups, hardware troubleshooting, and employee workstations.',
    responsibilities: [
      'Maintain office network switches, Mikrotik routers, VPN tunnels, and Ethio Telecom fiber links.',
      'Provide on-site technical support for Windows, macOS, and Linux workstations.',
      'Manage local data backups, antivirus endpoints, and user permissions.',
    ],
    requirements: [
      'Diploma or B.Sc. in Information Technology, Computer Science, or Electrical Engineering.',
      'Knowledge of TCP/IP networking, DNS, DHCP, and router configurations.',
      'Resident of Hawassa or willing to relocate immediately.',
    ],
    required_skills: ['IT & Networking', 'Hardware Troubleshooting', 'Linux', 'Network Administration'],
    preferred_skills: ['Mikrotik / Cisco Certified', 'Windows Server'],
    benefits: [
      'Stable regional role in Hawassa with housing support stipend',
      'Full medical insurance and mobile phone airtime allowance',
    ],
    deadline: new Date(Date.now() + 22 * 86400000).toISOString().split('T')[0],
    status: 'OPEN',
    is_featured: false,
    views_count: 198,
    applications_count: 7,
    created_at: new Date(Date.now() - 8 * 86400000).toISOString(),
  },
  {
    job_id: 8,
    company_id: 2,
    company_name: 'Kifiya Financial Technology',
    company_logo: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=150&q=80',
    company_slug: 'kifiya-fintech',
    company_city: 'Addis Ababa',
    title: 'Digital Marketing & Growth Associate',
    category_id: 5,
    category_name: 'Marketing & Sales',
    job_type: 'FULL_TIME',
    experience_level: 'ENTRY_LEVEL',
    location_city: 'Addis Ababa',
    location_subcity: 'Kirkos',
    workplace_type: 'HYBRID',
    salary_type: 'RANGE',
    salary_min: 16000,
    salary_max: 24000,
    currency: 'ETB',
    description: 'Execute innovative digital marketing campaigns, social media content in Amharic/English, and community engagement to drive adoption of digital financial services among Ethiopian youth and SMEs.',
    responsibilities: [
      'Create engaging content for Telegram channels, Facebook, LinkedIn, and TikTok.',
      'Analyze campaign analytics, click-through rates, and conversion metrics.',
      'Coordinate with tech teams on promotional giveaways, webinars, and university hackathons.',
    ],
    requirements: [
      'Degree in Marketing, Business Administration, Communications, or related field.',
      'Excellent Amharic and English copywriting skills.',
      'Familiarity with Canva, Meta Business Suite, and Telegram Bot broadcasting.',
    ],
    required_skills: ['Digital Marketing', 'Content Strategy', 'Social Media Management', 'Amharic Translation'],
    preferred_skills: ['Graphic Design Basics', 'Telegram Channel Growth'],
    benefits: [
      'Competitive base salary + quarterly campaign performance bonuses',
      'Professional training workshops in growth marketing',
    ],
    deadline: new Date(Date.now() + 19 * 86400000).toISOString().split('T')[0],
    status: 'OPEN',
    is_featured: false,
    views_count: 275,
    applications_count: 12,
    created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
  },
];

export const SEED_APPLICATIONS: Application[] = [
  {
    application_id: 1,
    job_id: 1, // Frontend React Developer at EthioTech
    user_id: 1, // Yohannes Tadesse
    student_name: 'Yohannes Tadesse',
    student_email: 'yohannes@student.aau.edu.et',
    student_phone: '+251 91 123 4567',
    student_avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
    student_headline: 'Junior Full-Stack Developer | AAU Software Eng. Graduate',
    job_title: 'Frontend React Developer',
    company_name: 'EthioTech Solutions PLC',
    company_logo: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=150&q=80',
    job_type: 'FULL_TIME',
    job_city: 'Addis Ababa',
    job_subcity: 'Bole',
    resume_url: '/uploads/resumes/yohannes_tadesse_cv.pdf',
    resume_filename: 'Yohannes_Tadesse_Software_Engineer_CV.pdf',
    resume_extracted_text: SEED_STUDENT_PROFILES[0].cv_extracted_text,
    cover_letter: 'Dear EthioTech Solutions Hiring Team,\n\nI am thrilled to apply for the Frontend React Developer role in Bole. As a graduating Software Engineer from Addis Ababa University (AAU) with production experience in React, TypeScript, and Tailwind CSS, I have followed EthioTech’s remarkable contributions to Ethiopian digital infrastructure with great admiration. I look forward to contributing my technical skills and energetic work ethic to your high-performing team.',
    additional_notes: 'Available for on-site interview in Bole on 24-hour notice.',
    status: 'SHORTLISTED',
    ai_match_score: 92,
    ai_match_feedback: {
      score: 92,
      matchedSkills: ['React', 'TypeScript', 'JavaScript', 'HTML/CSS', 'Tailwind CSS', 'Git & GitHub', 'Next.js'],
      missingSkills: ['Docker (Basics)'],
      experienceAnalysis: 'Candidate has a strong academic background in Software Engineering from AAU (3.82 GPA) and relevant internship experience at Addis Software PLC developing React UI components and REST APIs.',
      recommendation: 'Exceptional candidate with direct alignment to Frontend requirements. Highly recommended for technical interview.',
      strengthsSummary: [
        '3.82 GPA Software Engineering graduate from AAiT / AAU',
        'Proven React & TypeScript experience during internship at Addis Software',
        'Demonstrated capstone experience building localized Ethiopian billing systems',
      ],
      fitLevel: 'Exceptional',
    },
    created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    status_history: [
      { status: 'APPLIED', note: 'Application received via HireHub Ethiopia portal.', timestamp: new Date(Date.now() - 2 * 86400000).toISOString(), changed_by: 'System' },
      { status: 'UNDER_REVIEW', note: 'CV and GitHub portfolio reviewed by HR lead.', timestamp: new Date(Date.now() - 1.5 * 86400000).toISOString(), changed_by: 'Selamawit Bekele' },
      { status: 'SHORTLISTED', note: 'Profile cleared ATS screening with 92% AI Match Score. Shortlisted for Technical Interview round.', timestamp: new Date(Date.now() - 1 * 86400000).toISOString(), changed_by: 'Selamawit Bekele' },
    ],
  },
  {
    application_id: 2,
    job_id: 3, // Software Internship at EthioTech
    user_id: 1, // Yohannes Tadesse
    student_name: 'Yohannes Tadesse',
    student_email: 'yohannes@student.aau.edu.et',
    student_phone: '+251 91 123 4567',
    student_avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
    student_headline: 'Junior Full-Stack Developer | AAU Software Eng. Graduate',
    job_title: 'Software Development Internship — 2026 Batch',
    company_name: 'EthioTech Solutions PLC',
    company_logo: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=150&q=80',
    job_type: 'INTERNSHIP',
    job_city: 'Addis Ababa',
    job_subcity: 'Bole',
    resume_url: '/uploads/resumes/yohannes_tadesse_cv.pdf',
    resume_filename: 'Yohannes_Tadesse_Software_Engineer_CV.pdf',
    cover_letter: 'Applying for the 2026 internship batch to accelerate practical enterprise skills.',
    status: 'UNDER_REVIEW',
    ai_match_score: 96,
    ai_match_feedback: {
      score: 96,
      matchedSkills: ['JavaScript', 'HTML/CSS', 'Git & GitHub', 'React', 'Node.js', 'Problem Solving'],
      missingSkills: [],
      experienceAnalysis: 'Candidate exceeds the requirements for internship level with high academic distinction and verified full-stack project portfolio.',
      recommendation: 'Top-tier candidate for the internship program.',
      fitLevel: 'Exceptional',
    },
    created_at: new Date(Date.now() - 4 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    status_history: [
      { status: 'APPLIED', note: 'Application submitted.', timestamp: new Date(Date.now() - 4 * 86400000).toISOString(), changed_by: 'System' },
      { status: 'UNDER_REVIEW', note: 'Under review by talent acquisition.', timestamp: new Date(Date.now() - 3 * 86400000).toISOString(), changed_by: 'Selamawit Bekele' },
    ],
  },
  {
    application_id: 3,
    job_id: 4, // UI/UX Product Designer at Gebeya
    user_id: 2, // Bethlehem Haile
    student_name: 'Bethlehem Haile',
    student_email: 'bethlehem.haile@gmail.com',
    student_phone: '+251 92 345 6789',
    student_avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=300&q=80',
    student_headline: 'UI/UX & Product Designer | Figma & Design Systems',
    job_title: 'UI/UX Product Designer',
    company_name: 'Gebeya Tech Network',
    company_logo: 'https://images.unsplash.com/photo-1560179707-f14e90ef3623?auto=format&fit=crop&w=150&q=80',
    job_type: 'FULL_TIME',
    job_city: 'Addis Ababa',
    job_subcity: 'Bole',
    resume_url: '/uploads/resumes/bethlehem_haile_cv.pdf',
    resume_filename: 'Bethlehem_Haile_UIUX_Designer_CV.pdf',
    resume_extracted_text: SEED_STUDENT_PROFILES[1].cv_extracted_text,
    cover_letter: 'Dear Gebeya Tech Team,\n\nI am eager to apply as UI/UX Product Designer. My experience designing accessible interfaces for Ethiopian fintech and ride-hailing drivers has given me deep insights into building for our local context. I would love to bring this empathy and Figma expertise to Gebeya.',
    status: 'INTERVIEW',
    ai_match_score: 88,
    ai_match_feedback: {
      score: 88,
      matchedSkills: ['Figma', 'UI/UX Design', 'Design Systems', 'User Research', 'Prototyping', 'Tailwind CSS'],
      missingSkills: ['Micro-interactions in Framer'],
      experienceAnalysis: 'Strong product design portfolio demonstrating user research across Ethiopian market segments.',
      recommendation: 'Strong match for UI/UX Designer role. Candidate showcases excellent design rationale.',
      fitLevel: 'High',
    },
    created_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 0.5 * 86400000).toISOString(),
    status_history: [
      { status: 'APPLIED', note: 'Application received.', timestamp: new Date(Date.now() - 3 * 86400000).toISOString(), changed_by: 'System' },
      { status: 'UNDER_REVIEW', note: 'Portfolio evaluated.', timestamp: new Date(Date.now() - 2 * 86400000).toISOString(), changed_by: 'Talent Lead' },
      { status: 'SHORTLISTED', note: 'Shortlisted for interview.', timestamp: new Date(Date.now() - 1 * 86400000).toISOString(), changed_by: 'Talent Lead' },
      { status: 'INTERVIEW', note: 'Invited to Design Case Study Interview on Zoom / Bole Office.', timestamp: new Date(Date.now() - 0.5 * 86400000).toISOString(), changed_by: 'Talent Lead' },
    ],
  },
];

export const SEED_SAVED_JOBS = [
  { saved_id: 1, user_id: 1, job_id: 2, created_at: new Date().toISOString() },
  { saved_id: 2, user_id: 1, job_id: 6, created_at: new Date().toISOString() },
  { saved_id: 3, user_id: 2, job_id: 1, created_at: new Date().toISOString() },
];

export const SEED_NOTIFICATIONS: NotificationItem[] = [
  {
    notification_id: 1,
    user_id: 1,
    title: 'Application Shortlisted! 🎉',
    message: 'Your application for Frontend React Developer at EthioTech Solutions PLC was shortlisted! The recruitment team will contact you for the technical assessment.',
    type: 'SHORTLISTED',
    link_url: '/student/applications',
    is_read: false,
    created_at: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
  {
    notification_id: 2,
    user_id: 1,
    title: 'New High-Match Job in Addis Ababa',
    message: 'YeneHealth Digital PLC posted Mobile App Developer (Flutter) in Yeka matching your React & TypeScript skills.',
    type: 'JOB_ALERT',
    link_url: '/jobs/6',
    is_read: true,
    created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
  {
    notification_id: 3,
    user_id: 2,
    title: 'Interview Invitation 📅',
    message: 'Gebeya Tech Network has scheduled your UI/UX Case Study Interview. Check your applications dashboard for meeting details.',
    type: 'INTERVIEW_INVITE',
    link_url: '/student/applications',
    is_read: false,
    created_at: new Date(Date.now() - 0.5 * 86400000).toISOString(),
  },
  {
    notification_id: 4,
    user_id: 4, // Employer Selamawit
    title: 'New Applicant for Frontend React Developer',
    message: 'Yohannes Tadesse (AAU Software Eng graduate) applied with a 92% AI Match Score.',
    type: 'APPLICATION_UPDATE',
    link_url: '/employer/applicants',
    is_read: false,
    created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
];
